"""empty message

Revision ID: 9fc1d48ed044
Revises: 1dd23b8a86b7
Create Date: 2023-10-17 11:21:07.336998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc1d48ed044'
down_revision = '1dd23b8a86b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_memos_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_memos_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
